# Generated by Django 3.2.12 on 2022-09-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accords',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('accord_name', models.CharField(max_length=20)),
                ('accord_description', models.CharField(max_length=100)),
                ('accord_img', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'accords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccordsClasses',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('class_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'accords_classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HaveLists',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('is_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'have_lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfumeAccords',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'perfume_accords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfumes',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('perfume_name', models.CharField(max_length=100)),
                ('concentration', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('scent', models.CharField(max_length=100)),
                ('top_notes', models.CharField(max_length=300)),
                ('middle_notes', models.CharField(max_length=300)),
                ('base_notes', models.CharField(max_length=300)),
                ('item_rating', models.FloatField()),
                ('perfume_img', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('seasons', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=10)),
                ('longevity', models.IntegerField()),
                ('sillage', models.IntegerField()),
                ('wish_count', models.IntegerField()),
                ('have_count', models.IntegerField()),
            ],
            options={
                'db_table': 'perfumes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('review_img', models.CharField(blank=True, max_length=500, null=True)),
                ('total_score', models.IntegerField()),
                ('longevity', models.IntegerField()),
                ('sillage_score', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('like_count', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('like_seasons', models.CharField(max_length=10)),
                ('like_gender', models.CharField(max_length=10)),
                ('like_longevity', models.IntegerField()),
                ('like_timezone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'surveys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccordClass',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_accord_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccords',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_accords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetailLogs',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_detail_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=30)),
                ('profile_img', models.CharField(blank=True, max_length=500, null=True)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('seasons', models.CharField(blank=True, max_length=10, null=True)),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('accord_class', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSearchLogs',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'user_search_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishLists',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('is_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'wish_lists',
                'managed': False,
            },
        ),
    ]
